name: 'Sync closed task references'
description: 'Marks issues and PRs referenced from checkbox lists as completed'
inputs:
  github_token:
    description: 'Token to use for authenticated GitHub API requests'
    required: false
    default: ${{ github.token }}
  state:
    description: '(Optional) An explicit state to mark references - complete or incomplete'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
